on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - qa
          - uat

      suite:
        description: 'Suite'
        required: true
        type: choice
        options:
          - smoke
          - regression
