name: Automation Execution

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 1 * * *'

  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        required: true
        default: qa
        type: choice
        options:
          - qa
          - uat
          - prod

      browser:
        description: 'Select Browser'
        required: true
        default: chrome
        type: choice
        options:
          - chrome
          - firefox
          - edge

jobs:

  smoke:
    name: Smoke Suite
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: ${{ github.event.inputs.environment || 'qa' }}
      BROWSER: ${{ github.event.inputs.browser || 'chrome' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Verify Maven
        run: mvn -version

      - name: Install Dependencies
        run: mvn clean install -DskipTests

      - name: Execute Smoke Suite
        run: |
          echo "Environment = $ENVIRONMENT"
          echo "Browser = $BROWSER"

          mvn test \
          -Dsuite=smoke \
          -Denv=$ENVIRONMENT \
          -Dbrowser=$BROWSER

      - name: Upload Smoke Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Smoke-Report
          path: |
            reports/
            output.xml
            log.html
            report.html
          if-no-files-found: warn

  regression:
    name: Regression Suite
    needs: smoke
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: ${{ github.event.inputs.environment || 'qa' }}
      BROWSER: ${{ github.event.inputs.browser || 'chrome' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Verify Maven
        run: mvn -version

      - name: Install Dependencies
        run: mvn clean install -DskipTests

      - name: Execute Regression Suite
        run: |
          echo "Environment = $ENVIRONMENT"
          echo "Browser = $BROWSER"

          mvn test \
          -Dsuite=regression \
          -Denv=$ENVIRONMENT \
          -Dbrowser=$BROWSER

      - name: Upload Regression Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Regression-Report
          path: |
            reports/
            output.xml
            log.html
            report.html
          if-no-files-found: warn
